### ISSUE TITLE
Trouble running Assembly_Canu notebook

### ISSUE THREAD

**Issue by Mbf001** [genomicsITER/NanoDJ#1]
Hi, 
I'm checking the project,  and I found great the idea of putting all together an standard assembly pipeline of ONT data on a dockerfile. But I had some trouble running the canu notebook. In the first chunk of code when you launch the canu command I've got the invalid syntax error, and the command I think is right.
Adding the ```%%bash``` command  previous to canu run command  I got this error:

ERROR:  Failed to run gnuplot from 'gnuplot'.ERROR:  Set option gnuplot=<path-to-gnuplot> or gnuplotTested=true to skip this test and not generate plots.

I've tried to install gnuplot but, I couldn't. Any idea?

Thanks in advance

**Comment by hecrp** [comment]
Hi! Thank you for checking this project. The first syntax error you get is because the notebook kernel was probably python and not the bash kernel (we included a bash kernel to avoid using bash magics all the time in some notebooks). You can switch the kernel and run the bash commands without the %%bash magic.

We use the Canu tool to generate assemblies and the QUAST notebook to get html reports of comparison between assemblies. Canu can also generate plots and reports but we haven't included the dependencies (like gnuplot) to make this work yet. You should get the assembly without running the plot and report generation anyway.

I found this on the [Canu Parameter Reference](http://canu.readthedocs.io/en/latest/parameter-reference.html)

> gnuplotTested <boolean=false>
>     If set, skip the tests to determine if gnuplot will run, and to decide the image type to generate. This is used when gnuplot fails to run, or isn’t even installed, and allows canu to continue execution without generating graphs.

So you can put gnuplotTested=true on the Canu command and avoid getting that error message.

I will include these dependencies and put the correct kernel in each notebook by default to make things easier. Thank you very much for your time. I hope you find this project useful.

****EDIT (27/04/18):**** The last commit has the _gnuplot_ dependency solved and notebook kernels set up properly.  Also we have included Bandage and a notebook with the instructions.

**Comment by Kirovez** [comment]
For me the working name of the Docker container to run is genomicsiter/nanodj:latest
 instead nanodj:latest .

**Comment by genomicsITER** [comment]
Hi Kirovez, you are right. We have fixed the instructions in the README.md. Thank you for pointing the issue!
